# This file configures the analyzer to use the lint rules recommended by Flutter
# and enforces additional rules for better code quality.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Allow self-reference in factory constructors
    recursive_constructor_redirect: ignore

linter:
  rules:
    # Additional rules for better code quality
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    # avoid_returning_null_for_future - removed in Dart 3.3.0
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_overrides
    - unnecessary_statements
    - use_build_context_synchronously
